name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run make

      - name: Debug GitHub context
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub repository: ${{ github.repository }}"
          echo "GitHub actor: ${{ github.actor }}"

      - name: Publish to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}